import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { MyFloatingDock } from "@/components/floating-dock";

const poppins = Poppins({
  weight: ['400'],
  style: ['normal'],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} font-poppins antialiased`}
      >
        {children}
        <MyFloatingDock />
      </body>
    </html>
  );
}
