import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { MyFloatingDock } from "@/components/floating-dock";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistSans.variable} ${GeistSans.className} antialiased`}>
        {children}
        <MyFloatingDock />
      </body>
    </html>
  );
}
